spring:
    datasource:
        url: jdbc:mysql://localhost:3306/forgotDB?createDatabaseIfNotExist = true&allowPublicKeyRetrieval = true&useSSL = false
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 756822325867-rd7060leei7tq2b41tvgo4gk0o6fkrk9.apps.googleusercontent.com
              clientSecret: bncJLuKoIpph2avnTjLkmYxX
              redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 3763231927105422
              clientSecret: d876d7dbfa58516278db27ff266b86f0
              redirect-uri : "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d3e47fc2ddd966fa4352
              clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
              redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)      
    mail:
      host: smtp.gmail.com
      port: 587
      properties:
        mail:
          smtp:
            starttls:
              enable: true
              required: true
            auth: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
      username: zonionsapp@gmail.com
      password: zonions@123
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect


#Swagger Configuration
zonions:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.example.springsocial
    contact-name: zonions-supportgroup
    contact-email: zonions.supportgroup@foo.com
    swagger:
      enable: true